### ISSUE TITLE
Rename pixel and matrix types, Change single pixel type to strip

### ISSUE THREAD

**Issue by marmilicious** [wokwi/arduino-libraries#18]
1) As you were considering, yes I think it would be good to rename the pixel and matrix types to:
`wokwi-led-strip` and `wokwi-led-matrix`
(Beginners are often familiar with the name neopixel, but it's just a WS28** pixel, so probably better to keep it a generic name.)

And then later if there's a ring type, would that be `wokwi-led-ring`?

2) For the type of render, right now there is **individual** or **canvas**, and then if in canvas mode **pixelate** can be added.  What if pixelate is one of the render styles instead of a separate thing added on top of canvas?  So three render styles, instead of two with one having two modes, which seems harder to remember.

3) Canvas doesn't quite feel like the right name to me.  Maybe "blur" instead?

4) Change single pixel type to strip.  Strips of length 1 can of course be used for a single pixel.

**Comment by stevesigma** [comment]
Did anybody tried to create ring?

**Comment by urish** [comment]
Working on it: https://github.com/wokwi/wokwi-elements/pull/52

Preview: https://deploy-preview-52--wokwi-elements.netlify.app/?path=/story/neopixel-ring--ring-16

Would appreciate feedback (you are also invite to hop on the [discord chat](https://wokwi.com/discord) and discuss)
