### ISSUE TITLE
"Set project name..." doesn't seem to change anything?

### ISSUE THREAD

**Issue by marmilicious** [wokwi/arduino-libraries#24]
Using "Set project name..." and entering a new name doesn't seem to update anything anywhere.  It still showed the same name on the tab, and after saving it was still using the previous name as well.

**Comment by urish** [comment]
Added it last night - right now it changes the name that appears when you go to your [projects page](https://wokwi.com/arduino/projects). Did you expect it to change the title of the browser tab as well?

**Comment by marmilicious** [comment]
After changing it and making a copy, and also changing it and sharing the project and everything still having the same name I couldn't see it changing anything.  I didn't look on the projects page at that time.  I now see on my projects page that there are several versions (with different names as I was trying it) listed there.  

I guess I would expect the code tab (and also the browser tab) to update as well otherwise there's no immediate feedback and others like me might think nothing happened.

Also might be a good idea to make an easy way for the user to delete projects so they don't have to email you, yes?  That seems like it could get old fast.  :P

**Comment by marmilicious** [comment]
btw, if I go here:
https://wokwi.com/arduino/projects
how does it know what my projects are, when in the upper right corner it's asking me to Sign In?  If I'm not signed in how would it know my projects?

**Comment by urish** [comment]
Actually, that's a good piece of feedback. I'm going to move the "Rename project" option to the projects page, and add a "Delete" option there as well.

> how does it know what my projects are, when in the upper right corner it's asking me to Sign In? If I'm not signed in how would it know my projects?

It saves a reference to them in your browser's localStorage, signed by the server. If you eventually sign-in, they will eventually be migrated to your user. This allows people who haven't signed-in yet to still edit and "own" their projects

**Comment by urish** [comment]
Ok, both changes now implemented:

1. Renaming moved to the Projects page
2. Added an option to delete a project

p.s. we now have a pretty active [discord chat](https://wokwi.com/discord), I'd love to see you there as well

**Comment by marmilicious** [comment]
Hi Uri.  Sorry, haven't messed with this in awhile and just coming back to try this out a bit more now.  I'm still having trouble with renaming.  

I made a copy of a project, went to "My Projects" and renamed it.  After going to a different url and then coming back to My Projects page it had the old name again.  Found reloading the page corrected the displayed name, but a bit confusing to need to do this.  Then I opened the project and the ino tab still has the old name from the project I originally copied.  I can't figure out how to get the ino tab to show the new name?

Here's the project I was testing renaming with.  Name on My Projects page is color_blocks.ino, but that doesn't show up on the ino tab after opening the project.  https://wokwi.com/arduino/projects/289943317685207560

I also just noticed that the thumbnail image is old too.  It looks like the project thumbnail that this was copied from, not what it looks like now.

**Comment by urish** [comment]
Thanks for reporting @marmilicious! Sounds like some kind of caching issue on the server side, I'll investigate.

Can you share a screen shot of your /arduino/projects page?

**Comment by marmilicious** [comment]
On my phone now, but it still shows the same issue.

**Comment by urish** [comment]
Ok, I see why this is confusing: renaming the project on the "Projects page" **does not** rename the main sketch file in the project. They are two separate things, even though the project name is initially derived from the main sketch file. 

Do you think it'll make more sense if we change the default project name not to include the ".ino" extension?

Also, the project name should show up on the top of the project page, but currently only for [users with username](https://wokwi.com/makers). e.g. [This lovely flappy cat](https://wokwi.com/arduino/projects/286182458416693768)

**Comment by marmilicious** [comment]
Ok, here's screen shots of the discrepancy, but sounds like you see this now.  I see there is a rename option when in the project, was that just added, or was I completely missing it before? Anyway that's good.  

Is the name that shows up on My Projects page tied to the the .ino name at all or those can be separate?  Maybe useful, but possibly still confusing.

I actually like having the ino extension on there, particularly if there are multiple files (ie other tabs with .cpp, .h etc) making up the project.  I feel it helps clarify what's what to less experienced users.

![Screenshot_20210208-014259](https://user-images.githubusercontent.com/8573409/107324364-d51e4b80-6a5c-11eb-8125-d4cb1a6abd92.png)
![Screenshot_20210208-014346](https://user-images.githubusercontent.com/8573409/107324371-d780a580-6a5c-11eb-8287-ee0f6bb9b6ee.png)

**Comment by marmilicious** [comment]
Is there a way to have the image (where it shows a bit of the code and connected parts) on the My Projects be updated?  For example if I copy a project but then completely change a lot of stuff the snippet of code and parts it shows are completely wrong now.  If that's going to be visually useful to remembering/finding what project you want to open to work on then it's going to need to be somewhat accurate/current, right?

**Comment by tombo9999** [comment]
Same problem here :/ (see images)
What about having a filename and a description in "My Projects"?
So we can change the Description on "My Projects" page, and change the *.ino filename in the project itself.
![A Virtual Tape Measure](https://user-images.githubusercontent.com/1089595/107414609-87641a80-6b12-11eb-9e1b-ec2d0ad43f22.png)
![HelloWorld ino](https://user-images.githubusercontent.com/1089595/107414665-9cd94480-6b12-11eb-9fdd-1b0f3b1f27f9.png)

Or you can copy Tinkercad ;)
When you download the code, they generate the filename as follow: a_virtual_tape_measure1.ino

**Comment by tombo9999** [comment]
For instance, if you follow this [link](https://www.tinkercad.com/things/0zd3BIBui0w) then click on simulate, click on Code, you can download the code and the name is as I said in the previous post :)

**Comment by sutaburosu** [comment]
> Do you think it'll make more sense if we change the default project name not to include the ".ino" extension?

I think that might lead to less confusion. :+1:

**Comment by marmilicious** [comment]
> Do you think it'll make more sense if we change the default project name not to include the ".ino" extension?

I might have misunderstood earlier, I was thinking when in the project.  I agree it would be fine to not include the ino extension on the Project page.

**Comment by urish** [comment]
Hi Terry!

> Why is this proving so difficult to fix?! Surely it should be simple enough to provide a project rename feature that applies the name in BOTH places?

Just a matter of finding ~2 hours for implementing and testing it.

> BTW, I see that there used to be a Rename item in the drop-down menu of the main page (with the two tabs). At least can you just restore that please so that we can do it manually!

It's still there, if I understand correctly what you are referring to:

![image](https://user-images.githubusercontent.com/892318/137448441-10b83370-e9a6-43af-843a-3f36dbc784f7.png)

Thanks for the feedback!

**Comment by urish** [comment]
Hi Terry - the screen shot didn't make it through. Can you try attaching it through GitHub's web interface instead?

**Comment by terrypin999** [comment]
Weird, yet your attachments were OK in the emails I received! What's the obstacle?

Are you saying the **link** I sent doesn't work either? Works fine when I click it here, in GitHub. Here it is again:
[https://www.dropbox.com/s/pyxowyvkcc0apgq/Wokwi-NoRename.jpg?raw=1](url)

**Comment by terrypin999** [comment]
On Fri, 15 Oct 2021 01:05:22 -0700, you wrote:

>Hi Terry - the screen shot didn't make it through. Can you try attaching it through GitHub's web interface instead?

I sent the following from GitHub. Please confirm you now have my screenshot. 

More important - what's the fix? Is my version of Wokwi out of date or what?

--------------------

Weird, yet your attachments were OK in the emails I received! What's the
obstacle?

Are you saying the link I sent doesn't work either? Works fine when I click it
here, in GitHub. Here it is again:
https://www.dropbox.com/s/pyxowyvkcc0apgq/Wokwi-NoRename.jpg?raw=1

--------------------

Best wishes,

Terry
