### ISSUE TITLE
Wokwi library documenation and samples -- neopixel example error

### ISSUE THREAD

**Issue by drf5n** [wokwi/arduino-libraries#28]
I'm not sure who owns https://wokwi.com/arduino/libraries/Adafruit_NeoPixel/buttoncycler
but there is a error in the schematic where both wires to the button are connected to the same node.  This error makes the simulation non-functional.

The button could be repaired by moving the wire to a different node, as in https://wokwi.com/arduino/projects/325075981102482003

Adafruit says it is their code, but the simulation is yours: https://forums.adafruit.com/viewtopic.php?f=47&t=189023#p914891

It appears that https://wokwi.com/arduino/libraries/Adafruit_NeoPixel/buttoncycler is a child of  https://wokwi.com/arduino/libraries/Adafruit_NeoPixel which is in turn a child of https://wokwi.com/arduino/libraries which is a link of your front page at https://wokwi.com/

Could you please fix the button in https://wokwi.com/arduino/libraries/Adafruit_NeoPixel/buttoncycler

It would be nice if the code posted on the simulation referred to the author of the simulation and to the author of the code.  Such as:

```
// Code:  https://github.com/adafruit/Adafruit_NeoPixel/blob/master/examples/buttoncycler/buttoncycler.ino
// Simulation: https://wokwi.com/arduino/libraries/Adafruit_NeoPixel/buttoncycler

```

**Comment by urish** [comment]
Button fixed! Thanks for reporting
